# Generated by Django 2.1.5 on 2019-01-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order post', 'verbose_name_plural': 'Order posts'},
        ),
    ]
