# Generated by Django 2.1.5 on 2019-01-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_order_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
